### ISSUE TITLE
Ctrl Click Remove Space key Deletes keys

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#115]
### 2 Problems
1. Ctrl + Click Remove Space key Deletes keys
1. when removing key normally the key wont move all the way back to the play head

**Comment by SuddenDevelopment** [comment]
fun fact, they dont get deleted, they just occupy the same frame :)

**Comment by SuddenDevelopment** [comment]
resolved... there is a bit of a traffic jam effect when they all get next to each other, they will not overwrite each other anymore. to resolve the traffic jam effect might be more effort than it's worth right now because it would require a lot more logic and understandinf of all frames, not just the next one
